server:
  port: 8080
  servlet:
    context-path: /api
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haiguitangai?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# 接口文档
knife4j:
  enable: true
  openapi:
    title: Fantasy的接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.fantasy.haiguitangai.controller
